# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tonerecorder', '0002_recordedsyllable_content_as_wav'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxFreq11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='MinFreq11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
    ]
