# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0003_recordedsyllable_content_as_normalized_wav'),
        ('analytics', '0002_auto_20160507_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeakFreq18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreq28',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreq38',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreq48',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreq58',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreq68',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreq78',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreq88',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
    ]
