# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tonerecorder', '0003_recordedsyllable_content_as_normalized_wav'),
        ('analytics', '0003_peakfreq18_peakfreq28_peakfreq38_peakfreq48_peakfreq58_peakfreq68_peakfreq78_peakfreq88'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeakFreqChange28',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreqChange38',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreqChange48',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreqChange58',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreqChange68',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreqChange78',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
        migrations.CreateModel(
            name='PeakFreqChange88',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.FloatField()),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable')),
            ],
        ),
    ]
