# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_peakfreqchange28_peakfreqchange38_peakfreqchange48_peakfreqchange58_peakfreqchange68_peakfreqchange7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peakfreqchange28',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreqchange38',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreqchange48',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreqchange58',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreqchange68',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreqchange78',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreqchange88',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
    ]
