# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20160508_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxfreq11',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreq18',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreq28',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreq38',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreq48',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreq58',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreq68',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreq78',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
        migrations.AlterField(
            model_name='peakfreq88',
            name='recording',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tonerecorder.RecordedSyllable'),
        ),
    ]
